CREATE DATABASE PW2_ESCOLA

USE PW2_ESCOLA

CREATE TABLE CURSO(
IDCURSO INT NOT NULL PRIMARY KEY IDENTITY,
NOME_CURSO VARCHAR(30),
MODALIDADE VARCHAR(10),
CARGA_HORARIA INT
);

CREATE TABLE ALUNO(
IDALUNO INT NOT NULL PRIMARY KEY IDENTITY,
NOME_ALUNO VARCHAR(30),
CELULAR_ALUNO VARCHAR(11),
CPF_ALUNO VARCHAR(11),
ID_CURSO INT NOT NULL REFERENCES CURSO
);

select * from CURSO
select * from ALUNO